2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Configure stats pid to 29424
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Dell\.config\wandb\settings
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Loading settings from C:\Users\Dell\Documents\GitHub\smai-m24-assignments-HarshvardhanSingh841\assignments\3\wandb\settings
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'a3_2.py', 'program_abspath': 'C:\\Users\\Dell\\Documents\\GitHub\\smai-m24-assignments-HarshvardhanSingh841\\assignments\\3\\a3_2.py', 'program': 'C:\\Users\\Dell\\Documents\\GitHub\\smai-m24-assignments-HarshvardhanSingh841\\assignments\\3\\a3_2.py'}
2024-10-12 17:34:23,198 INFO    MainThread:29424 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:_log_setup():532] Logging user logs to C:\Users\Dell\Documents\GitHub\smai-m24-assignments-HarshvardhanSingh841\assignments\3\wandb\run-20241012_173423-xpcqad0b\logs\debug.log
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:_log_setup():533] Logging internal logs to C:\Users\Dell\Documents\GitHub\smai-m24-assignments-HarshvardhanSingh841\assignments\3\wandb\run-20241012_173423-xpcqad0b\logs\debug-internal.log
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:init():617] calling init triggers
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:init():667] starting backend
2024-10-12 17:34:23,199 INFO    MainThread:29424 [wandb_init.py:init():671] sending inform_init request
2024-10-12 17:34:23,204 INFO    MainThread:29424 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-12 17:34:23,204 INFO    MainThread:29424 [wandb_init.py:init():684] backend started and connected
2024-10-12 17:34:23,215 INFO    MainThread:29424 [wandb_init.py:init():779] updated telemetry
2024-10-12 17:34:23,215 INFO    MainThread:29424 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-12 17:34:23,537 ERROR   MainThread:29424 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-12 17:34:23,538 ERROR   MainThread:29424 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1252, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-12 17:34:24,070 WARNING MsgRouterThr:29424 [router.py:message_loop():77] message_loop has been closed
